torchrun \
    --nnodes=1 \
    --nproc_per_node=4 \
    --node_rank=0 \
    --rdzv_id=1 \
    --rdzv_backend=c10d \
    --rdzv_endpoint=localhost:12345 \
    pretrain_fm9g.py \
    --tensor-model-parallel-size 2 \
    --pipeline-model-parallel-size 2 \
    --num-layers 16 \
    --hidden-size 3584 \
    --ffn-hidden-size 18944 \
    --num-attention-heads 28 \
    --num-query-groups 4 \
    --swiglu \
    --disable-bias-linear \
    --max-position-embeddings 32768 \
    --seq-length 4096 \
    --micro-batch-size 1 \
    --global-batch-size 8 \
    --tokenizer-type SentencePieceTokenizer \
    --tokenizer-model jiuge/tokenizer/tokenizer.model \
    --vocab-size 73448 \
    --data-path data/wikitext-2/wikitext2_text_document_text_document \
    --bf16 \
    --lr 1e-4 \
    --lr-decay-style cosine \
    --lr-warmup-fraction 0.02 \
    --train-iters 1000 \
    --weight-decay 0.1 \
    --adam-beta1 0.9 \
    --adam-beta2 0.95 \
    --adam-eps 1e-6 \
    --use-distributed-optimizer \
    --overlap-grad-reduce \
    --overlap-param-gather \
    --log-interval 1 \
    --eval-interval 1000 \
    --recompute-activations \
    --distributed-backend nccl \
    --pos-bias-type rotary \
    --sequence-parallel \
    --use-flash-attn \
    --attention-backend flash \
    --num-layers-per-virtual-pipeline-stage 4 \
    --untie-embeddings-and-output-weights
