from dataclasses import dataclass, field
from typing import List

@dataclass
class ParallelStrategy:
    """
    Defines the optimal parallelization strategy generated by
    the Search Engine (Module C) or AI Advisor (Module D).
    """
    tp_size: int
    pp_size: int
    dp_size: int
    mbs: int
    gbs: int
    pp_layout: List[int]  # Layer distribution across PP stages, e.g., [8, 8]
    
    # Optional performance metrics
    source: str = "algorithm"  # Options: "algorithm" (Module C) or "ai" (Module D)

    # This field is derived from GBS, MBS, and DP
    num_micro_batches: int = field(init=False)

    def __post_init__(self):
        """
        Automatically calculate the number of micro-batches and 
        validate the consistency of the batch configuration.
        """
        denominator = self.mbs * self.dp_size
        
        # Guard rail: Ensure GBS is divisible by (MBS * DP)
        if self.gbs % denominator != 0:
            raise ValueError(
                f"Invalid training config: GBS ({self.gbs}) must be divisible by "
                f"MBS * DP_size ({denominator})."
            )
            
        self.num_micro_batches = self.gbs // denominator

    @property
    def bubble_fraction(self) -> float:
        """
        Calculate the theoretical pipeline bubble overhead ratio.
        Formula: (PP - 1) / num_micro_batches
        """
        if self.num_micro_batches == 0:
            return 1.0
        return (self.pp_size - 1) / self.num_micro_batches